#############################################################################
# Recuerda que los cooldowns están en segundos, haz la conversión adecuada. #
#############################################################################

game:
  coins-per-kill: 20

clans:
  price: 10000
  maximum-characters: 8

##################################################################################
# Este símbolo es el que deberán colocar para poder hablar por el chat del clan. #
##################################################################################
  symbol-chat: "@"
  members:
    max: 5

pearl:
  cooldown: 5

chests:
  cooldown: 10