#############################################################################
# Recuerda que los cooldowns están en segundos, haz la conversión adecuada. #
#############################################################################

game:
  coins-per-kill: 20
  addition-experience: 100
  golden-head:
    texture: "http://textures.minecraft.net/texture/421cab4095e71bd925cf464990e18e43adb725db7cc175fd9d1dec820914b3de"
    name: "&6Golden Head"
    lore:
      - "&7Esta increíble manzana puede ser"
      - "&7consumida en cuestión de segundos"
      - "&7y te dará increíbles efectos."
      - ""
      - "&7Recuerda que solo se puedes tener"
      - "&7como máximo 2 manzanas, y solo se te otorgaran"
      - "&7si tienes tu kit default."

clans:
  price: 10000
  maximum-characters: 15

  default-clan-name: "Sin clan"

# El tiempo es medido en minutos, al menos en este cooldown. #
  request-expiration: 2

# Este símbolo es el que deberán colocar para poder hablar por el chat del clan. #
  symbol-chat: "@"
  chat-format: "&9%player% &8>> &7%message%"
  members:
    max: 5

  colors-price:
    red: 4000
    gold: 5000
    green: 4000
    yellow: 5000
    light_purple: 6000
    white: 10000
    dark_blue: 6000
    dark_green: 4000
    dark_aqua: 8000
    dark_purple: 6000
    dark_gray: 7000
    gray: 2000
    black: 12000

combatlog:
  symbol: "▇"
  duration: 20
  drop-items: false
  block-commands:
    - "spawn"
    - "tpa"
    - "home"
    - "fly"
    - "gamemode"

backpack:
  price: 2500

  upgrades:
    tier-2: 10000
    tier-3: 15000
    tier-4: 25000
    tier-5: 50000
    tier-6: 80000

pearl:
  cooldown: 20

chests:
  cooldown: 360